import type { CapabilityManifest } from "@akcp/core";

export const automationServerCapabilities: CapabilityManifest[] = [
  {
    id: "akcp.auto.preview",
    name: "preview_application",
    kind: "tool",
    version: "0.1.0",
    description:
      "Analyzes a job posting URL to detect required fields before preparing. When to use: To inspect a form without side-effects. When not to use: If you intend to submit immediately. Side effects: none (external-read). Returns detected platform and fields.",
    riskLevel: "low",
    sideEffectLevel: "external-read",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.prepare",
    name: "prepare_application",
    kind: "tool",
    version: "0.1.0",
    description:
      "Drafts a job application and returns an approval token. When to use: To stage an application for human review. When not to use: If the user explicitly asks you to just read the job posting. Side effects: network call (external-read). Returns an Approval Token.",
    riskLevel: "medium",
    sideEffectLevel: "external-read",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.confirm",
    name: "confirm_application_submission",
    kind: "tool",
    version: "0.1.0",
    description:
      'Consumes an approval token to autonomously submit a job application. When to use: ONLY when you possess a valid approval token from prepare_application. When not to use: If you do not have human authorization. Side effects: External submission (external-submit). Example: `confirm_application_submission({ approvalToken: "xyz123", jobUrl: "http...", approverIdentity: "alice@corp.com" })`.',
    riskLevel: "critical",
    sideEffectLevel: "external-submit",
    requiredApproval: true,
  },
  {
    id: "akcp.auto.capture",
    name: "capture_job_posting",
    kind: "tool",
    version: "0.1.0",
    description:
      "Deferred feature to scrape job posting metadata. When to use: Feature is disabled. When not to use: Always. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "external-read",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.extract",
    name: "extract_platform_metadata",
    kind: "tool",
    version: "0.1.0",
    description:
      "Deferred feature to extract generic metadata. When to use: Feature is disabled. When not to use: Always. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.list_approvals",
    name: "list_pending_approvals",
    kind: "tool",
    version: "0.1.0",
    description:
      "Lists all currently pending (unconsumed) approval tokens. When to use: To verify if the human has authorized an action. When not to use: For any other lookup. Side effects: none (local-read). Returns array of tokens.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.revoke_approval",
    name: "revoke_approval",
    kind: "tool",
    version: "0.1.0",
    description:
      'Invalidates an existing approval token. When to use: If the user cancels the job application flow. When not to use: Without user request. Side effects: State mutation (local-write). Example: `revoke_approval({ approvalToken: "xyz123", approverIdentity: "alice@corp.com" })`.',
    riskLevel: "high",
    sideEffectLevel: "local-write",
    requiredApproval: false,
  },
  {
    id: "akcp.auto.list_audit_logs",
    name: "list_audit_logs",
    kind: "tool",
    version: "0.1.0",
    description:
      "Lists recent audit logs showing historical transactions (approved, rejected, revoked). When to use: To review past actions. When not to use: For pending actions. Side effects: none (local-read). Returns array of logs.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  // =====================================
  // Customer Support Capabilities
  // =====================================
  {
    id: "akcp.support.classify_intent",
    name: "classify_support_intent",
    kind: "tool",
    version: "0.1.0",
    description: "Classifies the intent of a customer support ticket based on text. When to use: To categorize inbound requests. When not to use: For anything else. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.retrieve_context",
    name: "retrieve_support_context",
    kind: "tool",
    version: "0.1.0",
    description: "Retrieves context (policies, macros, past tickets) relevant to a support ticket. When to use: To find related info. When not to use: Without ticket context. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.draft_reply",
    name: "draft_support_reply",
    kind: "tool",
    version: "0.1.0",
    description: "Drafts a reply to a support ticket using context. When to use: To generate a response. When not to use: To send a response. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.validate_reply",
    name: "validate_support_reply",
    kind: "tool",
    version: "0.1.0",
    description: "Validates a drafted support reply against compliance and policy rules. When to use: Before sending a reply. When not to use: For random text. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.redact_pii",
    name: "redact_support_pii",
    kind: "tool",
    version: "0.1.0",
    description: "Redacts or tokenizes PII from a support payload. When to use: To hide PII. When not to use: If PII is needed. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.preview_action",
    name: "preview_support_action",
    kind: "tool",
    version: "0.1.0",
    description: "Dry-runs a support action (e.g. refund, escalate) to preview its impact. When to use: To see what an action would do. When not to use: To execute the action. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "external-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.request_action_approval",
    name: "request_support_action_approval",
    kind: "tool",
    version: "0.1.0",
    description: "Stages a support action for human review and returns an approval token. When to use: To prepare an action for review. When not to use: To execute. Side effects: Creates pending approval.",
    riskLevel: "medium",
    sideEffectLevel: "external-read",
    requiredApproval: false,
  },
  {
    id: "akcp.support.record_resolution",
    name: "record_support_resolution",
    kind: "tool",
    version: "0.1.0",
    description: 'Consumes an approval token to autonomously execute a support action (e.g. issue refund, close ticket). When to use: To execute an approved action. When not to use: Without approval. Side effects: Executes action. Example: `record_support_resolution({ token: "123" })`.',
    riskLevel: "critical",
    sideEffectLevel: "external-submit",
    requiredApproval: true,
  },
  {
    id: "akcp.support.detect_knowledge_gap",
    name: "detect_support_knowledge_gap",
    kind: "tool",
    version: "0.1.0",
    description: "Detects gaps in current support documentation based on unresolved tickets. When to use: To analyze knowledge gaps. When not to use: For individual tickets. Side effects: none.",
    riskLevel: "low",
    sideEffectLevel: "local-read",
    requiredApproval: false,
  },
];
