/**
 * @module server
 * @description Configures tools for the MCP Automation Server with stateful HITL gates.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import crypto from 'node:crypto';
import {
  OKFDocumentService,
  OKFDocumentFactory,
  ApplicationStatus,
  mcpToolCallsCounter,
  mcpToolFailuresCounter,
  automationAttemptsCounter,
  automationApprovalRequiredCounter,
  automationSubmissionSuccessCounter,
} from '@ocf/core';
import { BrowserOrchestrator } from './automation/browser-orchestrator.js';

export const AutonomyLevel = {
  observe: 'observe',
  advise: 'advise',
  actWithApproval: 'act-with-approval',
} as const;

export type AutonomyLevel = (typeof AutonomyLevel)[keyof typeof AutonomyLevel];

// In-memory session store for stateful HITL validation tokens
interface PendingApplication {
  token: string;
  jobUrl: string;
  context: any;
  preparedFields: Record<string, string>;
  createdAt: number;
}

const pendingApplications = new Map<string, PendingApplication>();

export class OCFMcpAutomationServer {
  private readonly server: McpServer;
  private readonly docService: OKFDocumentService;
  private readonly orchestrator: BrowserOrchestrator;

  constructor(docService: OKFDocumentService) {
    this.docService = docService;
    this.orchestrator = new BrowserOrchestrator();

    // Create the MCP server instance
    this.server = new McpServer({
      name: 'open-career-format-automation-server',
      version: '0.1.0',
    });

    this.registerTools();
  }

  getServerInstance(): McpServer {
    return this.server;
  }

  private registerTools(): void {
    // Tool: preview_application
    this.server.tool(
      'preview_application',
      {
        jobUrl: z.string().url().describe('The job posting vacancy URL to preview'),
      },
      async ({ jobUrl }) => {
        mcpToolCallsCounter.add(1);
        try {
          const platform = this.detectPlatform(jobUrl);
          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  jobUrl,
                  platform,
                  requiredFields: ['first_name', 'last_name', 'email', 'resume_file', 'phone'],
                  estimatedAutonomyLevel: AutonomyLevel.actWithApproval,
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: prepare_application
    this.server.tool(
      'prepare_application',
      {
        jobUrl: z.string().url().describe('The target job posting vacancy URL'),
      },
      async ({ jobUrl }) => {
        mcpToolCallsCounter.add(1);
        automationAttemptsCounter.add(1);
        automationApprovalRequiredCounter.add(1);
        try {
          const context = await this.docService.getCareerContext();
          const token = crypto.randomBytes(16).toString('hex');

          // Pre-fill profile details logically
          const pref = context.preferences[0];
          const roles = pref?.frontmatter['roles'] || [];
          
          const preparedFields = {
            rolesApplied: Array.isArray(roles) ? roles.join(', ') : 'Software Engineer',
            status: 'Draft',
          };

          // Store application session state
          pendingApplications.set(token, {
            token,
            jobUrl,
            context,
            preparedFields,
            createdAt: Date.now(),
          });

          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  ok: true,
                  message: 'Application pre-filled and locked. Explicit human authorization is required to submit.',
                  approvalToken: token,
                  autonomyLevel: AutonomyLevel.actWithApproval,
                  preparedFields,
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: confirm_application_submission
    this.server.tool(
      'confirm_application_submission',
      {
        approvalToken: z.string().describe('The validation token generated by prepare_application'),
        dryRun: z.boolean().optional().default(false),
      },
      async ({ approvalToken, dryRun }) => {
        mcpToolCallsCounter.add(1);
        try {
          const pending = pendingApplications.get(approvalToken);
          if (!pending) {
            throw new Error(`Invalid or expired approval token: ${approvalToken}`);
          }

          // Trigger Playwright browser automation
          const result = await this.orchestrator.orchestrate(pending.jobUrl, pending.context, {
            headless: true,
            dryRun,
          });

          if (!result.success) {
            return {
              isError: true,
              content: [{ type: 'text', text: `Automation execution failed: ${result.errors?.join('\n')}` }],
            };
          }

          // Create and save OKF Application Document
          const appDoc = OKFDocumentFactory.createApplication(
            result.company,
            result.jobTitle,
            pending.jobUrl,
            {
              platform: result.platform,
              status: dryRun ? ApplicationStatus.Saved : ApplicationStatus.Applied,
              appliedAt: result.submittedAt,
            }
          );

          await this.docService.createDocument(appDoc);
          automationSubmissionSuccessCounter.add(1);

          // Clear token session
          pendingApplications.delete(approvalToken);

          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  ok: true,
                  message: dryRun
                    ? 'Dry-run application completed successfully.'
                    : 'Job application successfully submitted and registered in OKF bundle.',
                  conceptId: appDoc.conceptId,
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: capture_job_posting
    this.server.tool('capture_job_posting', { jobUrl: z.string().url() }, async ({ jobUrl }) => {
      mcpToolCallsCounter.add(1);
      return {
        content: [
          {
            type: 'text',
            text: `Captured job posting description from ${jobUrl}. (Mocked text representation)`,
          },
        ],
      };
    });

    // Tool: extract_platform_metadata
    this.server.tool('extract_platform_metadata', { jobUrl: z.string().url() }, async ({ jobUrl }) => {
      mcpToolCallsCounter.add(1);
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              platform: this.detectPlatform(jobUrl),
              requiresFormSubmit: true,
            }, null, 2),
          },
        ],
      };
    });
  }

  private detectPlatform(url: string): string {
    const lower = url.toLowerCase();
    if (lower.includes('linkedin')) return 'LinkedIn';
    if (lower.includes('gupy')) return 'Gupy';
    if (lower.includes('indeed')) return 'Indeed';
    return 'GenericPlatform';
  }
}
